use_frameworks!

target 'CocoapodsDemo_Example' do
  pod 'CocoapodsDemo2', :path => '../'
  #pod 'CocoapodsDemo2'
  pod 'CTAssetsPickerController',  '~> 3.3.0'
  pod 'SobotKit'
  pod 'Lightbox'
  pod 'Localize-Swift'
  pod 'PickerView'
  pod 'LocalizationKit'
  pod 'SKPhotoBrowser'

  target 'CocoapodsDemo_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  pod 'FBSnapshotTestCase' , '~> 2.1.4'
  pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
